import { Grid, Header, Image, Segment, Icon, Container, Divider, Button } from "semantic-ui-react"
import PageProps from "../../interfaces/page"

import cheap_desktop from '../../resources/basic_computer.png'
import gaming_desktop from '../../resources/gaming_computer.png'
import { Link, useNavigate } from "react-router-dom"

interface pic_text {
  picture: string
  header: string
  link: string
}

export const Home: React.FunctionComponent<PageProps> = props => {
  const desktops: pic_text[] = [ {picture: gaming_desktop, header: 'Build a computer today', link: '/build'}, {picture: cheap_desktop, header: 'Look in store', link: '/store'}]

  return (
    <>
    <HomepageHeading />
      <Segment>
        <Header textAlign="center" as='h1'>Looking to build a computer or purchase a part?<Header.Subheader>Look no further</Header.Subheader></Header>
        <Grid centered>
          <Grid.Row centered>
            <Segment.Group compact horizontal stackable>
            {desktops.map((elem, idx) => {
              return (
                <Link to={elem.link}>
                  <Segment padded>
                    <Image key={idx} size='big' src={elem.picture}></Image>
                    <Button fluid>
                    <Header as='h2' key={idx}>
                      <Icon color='green' size="mini" name='arrow right'/>
                      <Header.Content >{elem.header}</Header.Content>
                    </Header></Button>
                  </Segment>
                </Link>
              )
            })}
            </Segment.Group>
          </Grid.Row>
        </Grid>
        <Divider key='#about' />
        <Container text textAlign="center"><br/>
          {/* these blurbs were generated by chatgpt */}
          <Segment.Group raised>
          <Segment padded color='violet'>
            <Header icon><Icon name='group' color='violet' /><Header.Content>About us</Header.Content></Header><br/>
            Welcome to our DIY PC Building and Computer Store website! We are your one-stop destination for all your computer hardware needs. 
            Our website offers a wide selection of high-quality computer components, peripherals, and accessories at competitive prices. <br />
          </Segment>

          <Segment padded color='red'>
            <Header icon><Icon name='handshake' color='red' /><Header.Content>Here to help</Header.Content></Header><br/>
            We understand that building a PC can be a daunting task, especially for first-timers. That's why we are here to help you every step of the way. 
            Our website provides detailed guides and services to assist you in selecting the right components for your build, 
            as well as step-by-step instructions on how to assemble your PC. <br/>
          </Segment>
          
          <Segment padded color='orange'>
            <Header icon><Icon name='box' color='orange' /><Header.Content>Pre-built items</Header.Content></Header><br/>
            In addition to our DIY PC building resources, our website also offers a wide variety of pre-built desktops and laptops for those who prefer a more plug-and-play 
            approach. Our selection includes models from some of the most reputable brands in the industry, all at competitive prices. <br />
          </Segment>

          <Segment padded color='blue'>
            <Header icon><Icon name='comment' color='blue' /><Header.Content>Thank you</Header.Content></Header><br/>
            Thank you for choosing our DIY PC Building and Computer Store website as your go-to source for all things computer hardware. 
            We look forward to helping you build the PC of your dreams! <br /><br />
          </Segment>
          <Segment><Button  circular inverted color='green' icon='up arrow' content='Back to top' /></Segment>
          </Segment.Group>
        </Container>
        
      </Segment>
    </>
  )
}

{/* borrowed code from semanticui */}
const HomepageHeading = () => {
  const navigate = useNavigate()

  return (
    <Segment inverted padded>
    <Container text textAlign="center">
      <Header
        as='h1'
        content='BuildMaster'
        inverted
        style={{
          fontSize: '4em',
          fontWeight: 'normal',
          marginBottom: '1em',
          marginTop: '2em',
        }}
      />
      <Header
        as='h1'
        content='Lets build a computer together.'
        inverted
        style={{
          fontWeight: 'normal',
          marginTop: '1em',
        }}
      />
      <Button color='blue' size='huge' onClick={()=>navigate('/build')}>
        Get Started
        <Icon name='arrow circle right' />
      </Button>

      <Header
        as='h3'
        inverted
        style={{
          fontWeight: 'normal',
          marginTop: '3em',}}
        content='Need help deciding?'/>

        <Button 
        inverted
        color='orange' 
        size='big'
        content='Learn more'
        icon={<Icon name='arrow down' />}
        style={{ marginBottom: '4em' }} />
    </Container>
    </Segment>
  )
}
